### 4.1.3.	벡터의 방향

In [1]:
import math
rad = math.atan2(3, 2)  # 각도를 구한다（라디안）
th = math.degrees(rad)  # 도수법으로 변환한다
th

56.309932474020215

### 4.1.5　벡터의 연산

In [2]:
import numpy as np
a = np.array([2, 2])  # 벡터 a의 성분
b = np.array([2, -1]) # 벡터 b의 성분

In [3]:
# 덧셈
a + b

array([4, 1])

In [4]:
# 뺄셈
a - b

array([0, 3])

In [5]:
# 실수배
2 * a

array([4, 4])