### 5.2.1.	덧셈과 뺄셈

In [1]:
import numpy as np
A = np.matrix([[50, 40],[10, 10]])      # 행렬A（아침）
B = np. matrix([[30, 100], [20, 15]])   # 행렬B（밤）
A+B

matrix([[ 80, 140],
        [ 30,  25]])

### 5.2.2.	행렬의 실수배

In [2]:
A = np.matrix([[80, 140], [30, 25]])  # 행렬A
0.8 * A   # 0.8×A

matrix([[ 64., 112.],
        [ 24.,  20.]])

### 5.2.3.	곱셈

In [3]:
A = np.matrix([[1, 3], [2, 1]])          # 행렬A（곱해지는 쪽）
B = np.matrix([[150, 250], [130, 230]])  # 행렬B（곱하는 쪽）
A * B

matrix([[540, 940],
        [430, 730]])

### 5.2.4.	곱셈 규칙

In [4]:
A = np.matrix([[1, 3], [2, 1]])  # 행렬A（2×2행렬）
B = np.matrix([[145], [72]])     # 행렬B（2×1행렬）
A * B

matrix([[361],
        [362]])

### 5.2.5.	단위행렬

In [5]:
A = np.matrix([[1, 3], [2, 1]])  # 행렬A
E = np.matrix([[1, 0], [0, 1]])  # 단위행렬E
A * E

matrix([[1, 3],
        [2, 1]])

In [6]:
E * A

matrix([[1, 3],
        [2, 1]])

### 5.2.6.	역행렬

In [7]:
A = np.matrix([[5, 3], [2, 1]])  # 행렬A
B = np.linalg.inv(A)             # 역행렬（B）를 구한다
B

matrix([[-1.,  3.],
        [ 2., -5.]])

In [8]:
(A * B).astype(np.int64)

matrix([[1, 0],
        [0, 1]], dtype=int64)

### 5.2.7.	역행렬과 연립방정식

In [5]:
A = np.matrix([[5, 3], [2, 1]])  # 행렬A（미지수의 계수로 만든 행렬）
inv_A = np.linalg.inv(A)   # 행렬A의 역행렬
B = np.matrix([[9], [4]])  # 행렬B（연립방정식의 우변）
inv_A * B  # 역행렬×행렬B

matrix([[ 3.],
        [-2.]])

In [6]:
a = 5  # 행렬A（미지수의 계수）
b = 3
c = 2
d = 1
s = 9  # 행렬B（연립방정식의 우변）
t = 4
k = a*d - b*c  # 역행렬의 각각의 요소의 분모
x = ((d/k)*s) + ((-b/k)*t)  # 역행렬×행렬B
y = ((-c/k)*s) + ((a/k*t))
x, y

(3.0, -2.0)